# Generated by Django 5.2.8 on 2025-11-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'diagnosis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('encounter_id', models.AutoField(primary_key=True, serialize=False)),
                ('encounter_date', models.DateField()),
                ('visit_type', models.CharField(choices=[('Consultation', 'Consultation'), ('Follow-up', 'Follow-up'), ('Emergency', 'Emergency'), ('Procedure', 'Procedure'), ('Review', 'Review')], default='Consultation', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('treatment_plan', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'encounters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EncounterDiagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'encounter_diagnosis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EncounterProcedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'encounter_procedure',
                'managed': False,
            },
        ),
    ]
