# Generated by Django 5.2.8 on 2025-11-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.AutoField(primary_key=True, serialize=False)),
                ('generic_name', models.CharField(max_length=50)),
                ('brand_name', models.CharField(blank=True, max_length=50, null=True)),
                ('form', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Inhaler', 'Inhaler'), ('Drops', 'Drops'), ('Cream', 'Cream'), ('Other', 'Other')], default='Tablet', max_length=10)),
                ('strength', models.CharField(blank=True, max_length=30, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=30)),
                ('frequency_per_day', models.PositiveIntegerField(default=1)),
                ('duration_days', models.PositiveSmallIntegerField(default=7)),
                ('instructions', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prescription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Procedure1',
            fields=[
                ('procedure_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'procedure1',
                'managed': False,
            },
        ),
    ]
