# Generated by Django 5.2.8 on 2025-11-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('payer_name', models.CharField(max_length=60)),
                ('plan_name', models.CharField(blank=True, max_length=60, null=True)),
                ('policy_number', models.CharField(max_length=40, unique=True)),
                ('group_number', models.CharField(blank=True, max_length=40, null=True)),
                ('coverage_start', models.DateField()),
                ('coverage_end', models.DateField(blank=True, null=True)),
                ('coverage_percent', models.PositiveSmallIntegerField(default=80)),
                ('deductible_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('copay_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_primary', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'insurance_policy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('mrn', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patients',
                'managed': False,
            },
        ),
    ]
