# Generated by Django 5.2.8 on 2025-11-25 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={'managed': True},
        ),
    ]
