# Generated by Django 5.2.8 on 2025-11-25 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patients_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # For things that ALREADY exist in the DB (user_id column, idx_patient_name index),
        # we only update Django's migration state and skip actual SQL.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Empty: no ALTER TABLE / CREATE INDEX executed.
            ],
            state_operations=[
                migrations.AddField(
                    model_name='patients',
                    name='user',
                    field=models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AddIndex(
                    model_name='patients',
                    index=models.Index(
                        fields=['last_name', 'first_name'],
                        name='idx_patient_name',
                    ),
                ),
            ],
        ),

        # These can safely run against the DB.
        migrations.AlterField(
            model_name='patients',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
