# Generated by Django 5.2.8 on 2025-11-29 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patients_user_alter_patients_created_at_and_more'),
    ]

    operations = [
    ]
