# Generated by Django 5.2.8 on 2025-11-29 19:14

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20251129_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='user',
            field=models.OneToOneField(
                null=True,
                blank=True,
                to=settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE
            ),
        ),
    ]