# Generated by Django 5.2.8 on 2025-11-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors',
            options={'managed': True},
        ),
    ]
