# Generated by Django 5.2.8 on 2025-11-25 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctors_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # All the things that already exist in the DB (column + indexes)
        # are added ONLY to Django's state, not the actual database.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Empty: we don't change the DB because column + indexes already exist.
            ],
            state_operations=[
                migrations.AddField(
                    model_name='doctors',
                    name='department',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        db_column='department_id',
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='doctors',
                        to='doctors.department',
                    ),
                ),
                # If later you want the user field, add it in a NEW migration.
                # migrations.AddField(
                #     model_name='doctors',
                #     name='user',
                #     field=models.OneToOneField(
                #         blank=True,
                #         null=True,
                #         on_delete=django.db.models.deletion.CASCADE,
                #         to=settings.AUTH_USER_MODEL,
                #     ),
                # ),

                migrations.AddIndex(
                    model_name='doctors',
                    index=models.Index(
                        fields=['last_name', 'first_name'],
                        name='idx_doctor_name',
                    ),
                ),
                migrations.AddIndex(
                    model_name='doctors',
                    index=models.Index(
                        fields=['department'],
                        name='idx_doctor_department',
                    ),
                ),
            ],
        ),

        # These ALTERs can still run on the DB (usually safe/idempotent).
        migrations.AlterField(
            model_name='doctors',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
